micronaut:
  application:
    name: mmCarRecommender
    server:
      port: 8080

endpoints:
  health:
    enabled: true
    sensitive: false
#    details-visible: ANONYMOUS
netty:
  default:
    allocator:
      max-order: 3

mnm:
  car:
    model1: THAR
    model2: XUV300

carlisting:
  service:
    url: http://localhost:8081/cars
    name: localhost
    port: 8081

carinventory:
  service:
    url: http://localhost:8082/cars
    name: localhost
    port: 8082

